[versions]
kotlin = "2.1.10"
agp = "8.7.3"
gobley = "0.3.7"
android-compileSdk = "35"
kotlinx-coroutines = "1.9.0"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-atomicfu = { id = "org.jetbrains.kotlin.plugin.atomicfu", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
gobley-cargo = { id = "dev.gobley.cargo", version.ref = "gobley" }
gobley-uniffi = { id = "dev.gobley.uniffi", version.ref = "gobley" }

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
